### ISSUE TITLE
Configuración de moneda

### ISSUE THREAD

**Issue by sgobotta** [facttic/coopcycle-web#14]
Verificar que las siguientes stories se cumplan, realizando los cambios necesarios de configuración y UI/UX, de ser necesario. Implica incluír una nueva moneda en la base de datos. Potencialmente sea necesario ajustar traducciones, por eso es necesario realizar todo el recorrido de lxs distintxs usuarixs para asegurarnos que el cambio es consistente en los escenarios descriptos.

Como usuarix admin de CoopCycle
Necesito poder configurar la moneda en pesos argentinos
Para poder permitir a restaurants asignar precios a sus productos y recibir dinero en esa moneda

Como usuarix Restaurant
Necesito poder seleccionar una moneda en pesos argentinos
Para que usuarixs cliente puedan pagarlo

Como usuarix Cliente
Necesito visualizar mi orden de compra en pesos argentinos
Para poder pagarlo con los medios de pago existentes

**Comment by maxi3390** [comment]
Testeado desde admin, público y restaurant, cambios dentro de la rama `currency-config`.
El único "issue" que encontré es que en francés la moneda aparece como `$AR` y en los demás `locale`s aparece como `ARS`, estuve analizando de dónde sale esta configuración de moneda y no encontré la traducción corresponiente, pero no lo veo como un bug bloqueante, puede ser incluido dentro del #17.
