### ISSUE TITLE
Configuración de Impuestos

### ISSUE THREAD

**Issue by sgobotta** [facttic/coopcycle-web#15]
Para poder calcular los precios asignados a ordenes de compra, comisiones de la plataforma u otro tipo de transacción, es necesario configurar los impuestos relevantes a Argentina.

+ Agregar Argentina a tabla de impuestos por país
   + Actualmente, los valores de todos los países de la tabla están basados en [ésta web](https://www.avalara.com/vatlive/en/vat-rates/international-vat-and-gst-rates.html). Sigamos trabajando con la misma información.
+ Agregar todas las traducciones relevantes
   + Implica refactorización de código legacy
   + Actualización de traducciones en archivos yml
   + Detectar valores hardcodeados en francés

**Comment by maxi3390** [comment]
Related to #30

**Comment by maxi3390** [comment]
Existe una diferencia en la UI de impuestos respecto a la de productos, en la segunda no aparecen los decimales:

- Tabla de impuestos:
![image](https://user-images.githubusercontent.com/3445048/94314444-e146b800-ff56-11ea-9d0a-384f5a9e3939.png)

- Configuración de producto:
![image](https://user-images.githubusercontent.com/3445048/94314580-27038080-ff57-11ea-9c79-b19c5e75ae15.png)

**Comment by sgobotta** [comment]
> Existe una diferencia en la UI de impuestos respecto a la de productos, en la segunda no aparecen los decimales:
> 
>     * Tabla de impuestos:
>       ![image](https://user-images.githubusercontent.com/3445048/94314444-e146b800-ff56-11ea-9d0a-384f5a9e3939.png)
> 
>     * Configuración de producto:
>       ![image](https://user-images.githubusercontent.com/3445048/94314580-27038080-ff57-11ea-9c79-b19c5e75ae15.png)

Ohh si. Quizas sea un problema de UI, que no parsea los decimales. Asumo que en la DB están bien cargados.
