### ISSUE TITLE
Habilitar restaurant

### ISSUE THREAD

**Issue by sgobotta** [facttic/coopcycle-web#18]
+ Para que los restaurants se visibilicen en el mapa y portada de la web, deben estar habilitados.
  + Se debería poder realizar desde el dashboard de admin, pero por alguna razón la opción está deshabilitada
  + Actualmente se visibilizan en el mapa y portada para usuarios que acceden como `admin`, para los demás roles el restaurant está oculto.

**Comment by Cheche** [comment]
Cuando se edita un restaurant (por ejemplo, edición de franja horaria para habilitarlo en argentina), el restaurant se deshabilita por no tener una cuenta de PAGO asociada, por lo cual tampoco es posible habilitarlo desde el panel de administrador.

Si se ejecuta una Query en la base de datos para habilitar el restaurant (forzando a `true` el campo `enabled` de la tabla `restaurant`), al visualizar algun campo de dicho restaurant, el sistema se bloquea quedando en algún bucle aún no identificado, obteniendo finalmente un error 502.
