### ISSUE TITLE
Identificar / decidir como se maneja el repositorio

### ISSUE THREAD

**Issue by nicolasdimarco** [facttic/coopcycle-web#2]
Hay que definir la mejor dinámica para los cambios en el repo. 
Podemos hacer un  fork y trabajamos sobre ese repositorio. Tratando de hacer cambios reutilizables y hacer PR en el repo origen.

**Comment by sgobotta** [comment]
Concluímos que:

+ El repositorio se va a basar en un fork del 14/08/2020
+ Las implementaciones entendibles/modulares servirán como insumo para contribuciones a la plataforma general d CoopCycle (podemos marcar esas issues con un tag al estilo `future pr` o parecido)
+ Las implementaciones no extendibles posiblemente sean las referentes a la puesta en producción (archivos de configuración, docker, etc.)
