### ISSUE TITLE
Implementar soporte para pedido http de `preferences` de Mercadopago

### ISSUE THREAD

**Issue by sgobotta** [facttic/coopcycle-web#20]
Implementar el paso sugerido en la [documentación de Mercadopago](https://www.mercadopago.com.ar/developers/en/guides/online-payments/marketplace/checkout-pro/create-marketplace/), de manera que la plataforma perciba una suma determinada de dinero cada vez que se realiza una transacción.

Fragmento del comentario de mex, en el [issue del repositorio de la app](https://github.com/coopcycle/coopcycle-app/issues/729), en cuanto a la implementación de `preferences` para Mercadopago.

> As you are suggesting, everything can be done server-side to generate the Mercado Pago Preference.
> So either we create a new endpoint, like GET /api/orders/{id}/mercado-pago-preference, or we add a new property to the order payload, like mercadopagoPreferenceId, which is calculated each time the order is updated (see OrderPaymentProcessor which could be adapted for this)

En lugar de crear un nuevo endpoint, que complejizaría el trabajo (generar más documentación, implementar tests, ...), creemos que por ahora es suficiente con la opción de agregar un atributo más.

**Comment by maxi3390** [comment]
En este issue y el #22 va a estar trabajando @Cheche, lo taggeo para que le puedan dar acceso al repo.

**Comment by maxi3390** [comment]
Quedan los cambios en la rama `mercadopago-preferences` pero se cierra porque no se va a implementar por el momento.

**Comment by sgobotta** [comment]
Se resuelve la integración de `/preferences` para la aplicación mobile en éste [commit](https://github.com/facttic/coopcycle-app/commit/54f5599875ce3cc1817f0ad63a4a9abdc365b2d2) del repositorio **facttic/coopcycle-app**
