### ISSUE TITLE
Customizar formularios con registro de restaurantes

### ISSUE THREAD

**Issue by nicolasdimarco** [facttic/coopcycle-web#3]
En francia utilizan por ejemplo otros campos que acá no se usan para registrar un resto.

Habría que repasar todos los forms y anotar qué cambios hacen falta. Luego ver si hay que hacer más tareas en base a este primer relevamiento. 

Un cambio ejemplo sería agregar CUIT.

**Comment by sgobotta** [comment]
**In order to**  `achieve Localization for Argentina`, the following sections have to be taken into account for refactoring

### Restaurants

+ NEW RESTAURANT `/admin/restaurants/new`
    + Refactor `SIRET`, `VAT` and `RCS` numbers
    + Settlement Section
        + Check that settlement (Responsible for the cost of the Stripe fees, refunds, and chargebacks) has no conflicts with MercadoPago features. (same as EDIT restaurant)

+ EDIT RESTAURANT `/admin/restaurants/:id`
    + General Section
        + Address (localized by `COOPCYCLE_COUNTRY` in `.env` file)
    + Telephone (format should be localized to Argentina)
    + Payment Section
      + Stripe details. Have to be refactored to MercadoPago details. Does it make sense to allow a resturant to manage the MercadoPago account?
    + Settlement Section
      + Check that settlement (Responsible for the cost of the Stripe fees, refunds, and chargebacks) has no conflicts with MercadoPago features. (same as NEW restaurant)

+ RESTURANT PREPARATION (Statistics) `/admin/restaurants/:id/stats`
    + Refactor ***VAT*** to **IVA**

### Stores

+ STORE `/admin/stores/new`
    + Refactor `SIRET`, `VAT` and `RCS` numbers

### Admin Dashboard



+ Taxation `/admin/settings/taxation`
    + Add Argentina taxation details to the table
+ Zones `/admin/zones`
    + Determine whether a GeoJSON file is a must for the platform to work properly in Argentina

**Comment by sgobotta** [comment]
Arranqué a trabajar en una branch `country-ar-new-restaurant-form` que sale de master (tiene todo lo de mercadopago tambien). ya empecé a hacer cambios en las traducciones y el agregado de CUIT en el formulario de creación de restaurant.

**Comment by sgobotta** [comment]
Esta tarea resulta mas general y será contemplada en pequeños issues descriptos en #12 

Queda referenciado este issue para consultas.
