### ISSUE TITLE
Configurar apikeys múltiples

### ISSUE THREAD

**Issue by nicolasdimarco** [facttic/coopcycle-web#4]
Si vamos a meter keys para MP deberían convivir con las de Stripe.

**Comment by alexsegura** [comment]
Hola! 

Hemos decidido utilizar [Mercado Pago](https://www.mercadopago.com) como gateway "alternativa", porque cobre toda Latino America, arreglando el problema tambien para lxs amigxs de Costa Rica, Brazil, Guatemala...

Desde coopcycle/coopcycle-web@cb24d2d90a33177acba5274523e598e333c6b3f3, es posible configurar credenciales para Mercado Pago, cuando el pais esta en la lista de paises que cobre Mercado Pago. 

Entonces creo que puedes cerrar esta issue 🙂

**Comment by sgobotta** [comment]
> @alexsegura 
> Hola!
> 
> Hemos decidido utilizar [Mercado Pago](https://www.mercadopago.com) como gateway "alternativa", porque cobre toda Latino America, arreglando el problema tambien para lxs amigxs de Costa Rica, Brazil, Guatemala...
> 
> Desde [coopcycle/coopcycle-web@cb24d2d](https://github.com/coopcycle/coopcycle-web/commit/cb24d2d90a33177acba5274523e598e333c6b3f3), es posible configurar credenciales para Mercado Pago, cuando el pais esta en la lista de paises que cobre Mercado Pago (mira la clase [GatewayResolver](https://github.com/coopcycle/coopcycle-web/blob/a6c4135f873107a682026f0277b63f4ba5086f17/src/Payment/GatewayResolver.php))
> 
> Entonces creo que puedes cerrar esta issue slightly_smiling_face

Alex, gracias por la respuesta. Ayer a última descubrimos que estaban trabajando sobre MercadoPago y pudieron cerrar algunos PR. Definitivamente es de gran utilidad para la localización de CoopCycle en Argentina. Vamos a estar haciendo pruebas y seguramente aportando al [issue de documentación](https://github.com/coopcycle/coopcycle-docs/issues/44) :tada:

**Comment by sgobotta** [comment]
La lógica funciona de la siguiente manera:

Si en el ambiente de tu instancia figura `COOPCYCLE_COUNTRY=ar`, entonces tu medio de pago es `MercadoPago`, de esa manera conviven los distintos pagos para distintas regiones/países. En otras palabras, cuando lo configuramos para `ar`, el formulario es distinto.

**Comment by sgobotta** [comment]
> La lógica funciona de la siguiente manera:
> 
> Si en el ambiente de tu instancia figura `COOPCYCLE_COUNTRY=ar`, entonces tu medio de pago es `MercadoPago`, de esa manera conviven los distintos pagos para distintas regiones/países. En otras palabras, cuando lo configuramos para `ar`, el formulario es distinto.
> 
> Ya existen campos para las keys de MP de TEST y LIVE. las de live no funcionan aún.

Se está trabajando [acá](https://github.com/coopcycle/coopcycle-web/pull/1655)

**Comment by sgobotta** [comment]
Ya se resolvió el conflicto del formulario que no mostraba las api keys de producción de MP. Y se pueden configurar distintas api keys, dependiendo del país declarado en `.env`
