### ISSUE TITLE
Refactor de cada formulario que interactua con medios de pago

### ISSUE THREAD

**Issue by nicolasdimarco** [facttic/coopcycle-web#5]
Si bien entendemos que está preparado para aceptar múltiples gateways de pago, tenemos que revisar las interfaces para asegurarnos de que también se encuentran preparadas.

**Comment by alexsegura** [comment]
Hola!

En la pull request coopcycle/coopcycle-web#1655, hay una implementacion (custom) para Mercado Pago en frontend. Espero terminarla para este fin de semana. 

Un sistema de "mixin" ha sido introducido en coopcycle/coopcycle-web@8247f439de774728c2070e5b069e1697e1b4797f, para que sea mas facil añadir mas gateways.

**Comment by alexsegura** [comment]
Tambien, hay que pensar en la app movil. 

He abierto coopcycle/coopcycle-app#729 para no olvidar.

**Comment by sgobotta** [comment]
> Tambien, hay que pensar en la app movil.
> 
> He abierto [coopcycle/coopcycle-app#729](https://github.com/coopcycle/coopcycle-app/issues/729) para no olvidar.

Perfecto @alexsegura, voy a estar investigando ese issue y pensar en agregarlo a nuestra planificación de trabajo

**Comment by sgobotta** [comment]
Todo refactor va a ser contemplado en las tareas de la epic #21
