### ISSUE TITLE
Configurar MP para el proyecto, para tener la cuenta con la info necesaria para empezar a probar

### ISSUE THREAD

**Issue by nicolasdimarco** [facttic/coopcycle-web#6]
Hay que crear una cuenta de MP para FACTTIC de manera de usarla en el proyecto.

**Comment by alexsegura** [comment]
MP = Mercado Pago? 🙂 

Si haceis esto, seria bien documentarlo. He abierto esta issue coopcycle/coopcycle-docs#44

**Comment by sgobotta** [comment]
> MP = Mercado Pago? slightly_smiling_face
> 
> Si haceis esto, seria bien documentarlo. He abierto esta issue [coopcycle/coopcycle-docs#44](https://github.com/coopcycle/coopcycle-docs/issues/44)

Si, durante el proceso de prueba de la nueva integración iremos documentando el paso a paso. Si coopcycle ya cuenta con un formato específico para documentar sería interesante continuar con el standard

**Comment by alexsegura** [comment]
Pues si modificas el proyecto [coopcycle-docs](https://github.com/coopcycle/coopcycle-docs) llega directamente en [docs.coopcycle.org](https://docs.coopcycle.org), es la documentacion "oficial". El formato es Markdown, muy sencillo.

**Comment by sgobotta** [comment]
Vamos a estar trabajando en los items descriptos en [pull/1655]*https://github.com/coopcycle/coopcycle-web/pull/1655)

**Comment by sgobotta** [comment]
Ya está creada la cuenta de facttic de gmail, junto con las credenciales de prueba y producción. Mas información en el documento interno,
