### ISSUE TITLE
Crear cuenta de Google (para MP) de FACTTIC

### ISSUE THREAD

**Issue by nicolasdimarco** [facttic/coopcycle-web#7]
Además de crear la cuenta de google necesitamos:

+ [x] habilitar un medio de pago (obligatorio). *Seguramente el bajo consumo del ambiente de dev no genere gastos)*
+ [x] habilitar las APIS para: Geocoding, Web maps, Android maps

**Comment by sgobotta** [comment]
> Update de tareas a realizar en la descripción

**Comment by pablovannini** [comment]
generada la cuenta y habilitado el medio de pago
