### ISSUE TITLE
Investigar la implementación de múltiples gateways

### ISSUE THREAD

**Issue by nicolasdimarco** [facttic/coopcycle-web#8]
Hay que entender hasta qué punto está implementado. 
Ingresar la configuración de MP y ver si funciona.

**Comment by sgobotta** [comment]
La integración de MercadoPago está hecha por la mitad, o menos.

La paltaforma ya cuenta con una configuración simple, que funciona a medias:

+ se cargan api keys de prueba
+ está configurada la verificación de usuarios de mercadopago (validación en MP y redirección a la plaaforma)
+ no se cargan api keys de producción
+ no se conectan a los restaurants
+ aún no hay splitting

La modularización con cualquier medio de pago está bastante verde, de hecho recién ahora se está empezando a desacoplar Stripe de los componentes y aún hay lógica mezclada entre MP y Stripe. Ejemplo:

+ `src/Service/MercadopagoManager.php`

Propongo que se continúe con las tareas descriptas en #6

**Comment by sgobotta** [comment]
Flujo de información, relevante al medio de pago

Aplicaciones cliente (app)

+ se obtiene la configuración inicial desde el endpoint `/api/settings`
+ se setea en el estado del cliente `country`, public keys, entre otros datos que no vienen al caso. *Ver el archivo `settings.features`*
+ es necesario agregar nuevos atributos a la respuesta de ese endpoint para distinguir qué medio de pago utilizar, y obtener las public keys de ese medio de pago

**Comment by sgobotta** [comment]
En base a esta investigación se desprenden tareas relevantes al gateway de pagos `Mercadopago`, ya se está trabajando en un flujo simple de pagos. Los siguientes pasos, referenes al gateway de pago, se discutiran en #21
